package client;

import Erros.EventoException;
import Erros.EventoInvalidoException;
import java.awt.Desktop;
import java.io.File;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

public class Inicio extends javax.swing.JFrame {

    private Cliente servidor;
    private Socket socket;
    private ObjectOutputStream enviar;
    private ObjectInputStream receber;
    
    public Inicio() {

        fazerConexao();
        
        initComponents();
        this.setTitle("Bem vindo ao chat - " + this.servidor.getUsuario());
        
        Saida.setSaida(txtMensagens);
        
        servidor.setListaChat(listaChat);
        servidor.start();
        servidor.setPagina(this);
        
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }
    
    public void fazerConexao() {
        try {
            servidor = new Cliente();
        } catch (IOException ex) {
            int opcao = JOptionPane.showConfirmDialog(null, "Ocorreu um erro na conexão com o servidor, deseja tentar novamente?");
            
            if(opcao == 0) {
                this.fazerConexao();
            }else {
                throw new RuntimeException("Não foi possível iniciar o chat");
            }
        }
        
        if(!fazerLogin())
            fazerConexao();
    }
    
    public void abrirArquivoRecebido(String origem, File arquivo) {
        int opcao = JOptionPane.showConfirmDialog(null, "Arquivo recebido de " + origem + ", deseja abrir?");
            
        if(opcao == 0) {
            Desktop dt = Desktop.getDesktop();
            try {
                dt.open(arquivo);
            } catch (IOException ex) {
                ex.getStackTrace();
            }
        }
    }
    
    public boolean fazerLogin() {
        try {
            servidor.fazerLogin(JOptionPane.showInputDialog("Digite seu usuário: "));
            
            return true;
            
        } catch (IOException ex) {
            throw new RuntimeException("Não foi possível iniciar o chat: " + ex.getMessage());
            
        } catch (EventoException | EventoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEnviarMensagem = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaChat = new javax.swing.JList<String>();
        btnTodos = new javax.swing.JButton();
        btnEnviarMensagem = new javax.swing.JButton();
        btnEnviarArquivo = new javax.swing.JButton();
        labelUsuario = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagens = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("janelaPrincipal"); // NOI18N
        setResizable(false);

        txtEnviarMensagem.setColumns(20);
        txtEnviarMensagem.setRows(5);
        jScrollPane1.setViewportView(txtEnviarMensagem);

        listaChat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listaChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaChatMouseClicked(evt);
            }
        });
        listaChat.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaChatValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaChat);

        btnTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTodos.setText("Todos");
        btnTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTodosMouseClicked(evt);
            }
        });
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        btnEnviarMensagem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEnviarMensagem.setText("Enviar");
        btnEnviarMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMensagemMouseClicked(evt);
            }
        });
        btnEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensagemActionPerformed(evt);
            }
        });

        btnEnviarArquivo.setText("Enviar Arquivo");
        btnEnviarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarArquivoActionPerformed(evt);
            }
        });

        labelUsuario.setAlignment(java.awt.Label.CENTER);
        labelUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelUsuario.setText("Todos");

        txtMensagens.setEditable(false);
        txtMensagens.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(txtMensagens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEnviarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnviarArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        this.listaChat.clearSelection();
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensagemActionPerformed
        
        if(this.txtEnviarMensagem.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o texto da mensagem para enviar");
            return;
        }
        
        try {
            this.servidor.enviarMensagem(this.txtEnviarMensagem.getText(), this.listaChat.getSelectedValue());
            this.txtEnviarMensagem.setText("");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao enviar a mensagem, tente novamente.");
        }
        
    }//GEN-LAST:event_btnEnviarMensagemActionPerformed

    private void btnEnviarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarArquivoActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File arquivo = jfc.getSelectedFile();
            try {
                String textoMensagem = JOptionPane.showInputDialog("Arquivo '" + arquivo.getName() + "' selecionado, digite a mensagem: ");
                servidor.enviarMensagem(textoMensagem, this.listaChat.getSelectedValue(), arquivo);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao enviar a mensagem, tente novamente.");
            }
        }
    }//GEN-LAST:event_btnEnviarArquivoActionPerformed

    private void listaChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaChatMouseClicked
        this.listaChat.getSelectedValue();
    }//GEN-LAST:event_listaChatMouseClicked

    private void btnTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTodosMouseClicked
        this.listaChat.clearSelection();
    }//GEN-LAST:event_btnTodosMouseClicked

    private void listaChatValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaChatValueChanged
        if(this.listaChat.isSelectionEmpty())
            this.labelUsuario.setText("Todos");
        else
            this.labelUsuario.setText(this.listaChat.getSelectedValue());
    }//GEN-LAST:event_listaChatValueChanged

    private void btnEnviarMensagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMensagemMouseClicked
        
    }//GEN-LAST:event_btnEnviarMensagemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarArquivo;
    private javax.swing.JButton btnEnviarMensagem;
    private javax.swing.JButton btnTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label labelUsuario;
    private javax.swing.JList<String> listaChat;
    private javax.swing.JTextArea txtEnviarMensagem;
    private javax.swing.JEditorPane txtMensagens;
    // End of variables declaration//GEN-END:variables
}
